### ISSUE TITLE
Remove manual page load events from the Glean Debug Ping Viewer

### ISSUE THREAD

**Issue by rosahbruno** [mozilla/debug-ping-view#147]
https://bugzilla.mozilla.org/show_bug.cgi?id=1875839

We tested the Glean.js built-in page load events in the debug ping viewer and everything looks as expected. This means that we can remove the manual instrumentation for page loads and just rely on the built-in events instead.

**Comment by abhi-agg** [comment]
Closing this one as https://bugzilla.mozilla.org/show_bug.cgi?id=1875839 is done.
