### ISSUE TITLE
Some new tagged pings aren't showing on dev, but are showing in prod

### ISSUE THREAD

**Issue by chutten** [mozilla/debug-ping-view#184]
We ingested some pings tagged with `jeddai-test` in the past couple of days and they appropriately show [on prod](https://debug-ping-preview.firebaseapp.com/pings/jeddai-test), but not [on dev](https://glean-debug-view-dev-237806.firebaseapp.com/).

That's weird, isn't it?

**Comment by rosahbruno** [comment]
I was playing around with the cloud functions deployment the other day. Originally, it didn't seem like the garbage collector was working, but after a few days it seems to have corrected itself. Both environments now have the same number of debug tags; dev no longer has an extra few hundred. It is now respecting the 21 days count again.

I will keep an eye on this and reopen the issue if it starts again.
