### ISSUE TITLE
Ping Details views don't include the ping type

### ISSUE THREAD

**Issue by chutten** [mozilla/debug-ping-view#79]
When looking at a ping detail page, nowhere does it mention the name of the ping. It'd be nice if it did, especially for people who are linked directly to a ping detail page using the nice, new permalinks.

**Comment by Medhansh404** [comment]
heyy!!! @rosahbruno i can def take a look into the issue if it is not in some way addressed. also would love if you could elaborate a bit @chutten about the issue!!!

**Comment by chutten** [comment]
Certainly! When you click on a "ping detail page" (which is generated from the `ShowRawPing` component in `src/components/ShowRawPing/components/ShowRawPing.js`) you get a lovely view like this:
![image](https://github.com/mozilla/debug-ping-view/assets/1123376/6ad349af-6f39-4f6e-9d2e-313bf8e4289c)

This is an "events" ping, that is a ping with a doctype of `events`. Pings can have all sorts of doctypes (e.g. [here's the list of available ping doctypes for Firefox for Android](https://dictionary.telemetry.mozilla.org/apps/fenix?itemType=pings&page=1)) and which doctype it is makes a _big difference_ for interpreting the data within it.

I think the best place for such information would be somewhere in the top matter. If that doesn't work out, then maybe we can put a fake field in `ping_info`.

Does that help @Medhansh404 ?

**Comment by Medhansh404** [comment]
yeah we can do that! I'll look into this, Thank you for the follow up @chutten :)

**Comment by rosahbruno** [comment]
Haven't heard anything on this one for a while and we are having a tech-debt week, so I fixed this.
